### ISSUE TITLE
Revisit readme

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz-server#27]
The readme ( as all readmes do) has become outdated

**Comment by Samywamy10** [comment]
I'm trying to run this project but having troubles...+1

**Comment by Janekdererste** [comment]
Sorry for the late response @Samywamy10. I've updated the readme just now and I will put example configuration files into the project's wiki. I am aware that this documentation might not be comprehensive to get everything started. Feel free to contact me for detailed explenation
