### ISSUE TITLE
Create Tags for files

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/viz-server#53]
Within a project we need to order resources. Especially files must have a hirachy, so that the same file names (e.g. output_network.xml) may appear several times within a project. 

Most people sort their projects in runs. Though some people might not. 

To keep things flexible, order will be created by introducing tags on files and visualizations. This way everyone can have as much hirachy as they want. Also, files at the root of the project are possible, e.g. realworld counts for comparison. 

Instead of also turning Projects into tags, we'll keep this as the root element of structure for now, since projects are the point where we are currently managing access for othe users.

**Comment by Janekdererste** [comment]
Postgresql has somethin like that https://www.postgresql.org/docs/11/ltree.html

**Comment by billyc** [comment]
- Let's make sure that tags can have tags.  OK well, let's call them types or labels or something.  
- This way I can say "Show me all tags that are of type RUN

**Comment by Janekdererste** [comment]
Tags now have Tags. it's called type.
