### ISSUE TITLE
API calls to /projects/id/visualizations/ are not returning project parameters

### ISSUE THREAD

**Issue by billyc** [matsim-org/viz-server#83]
In the UI Code, FileAPI.fetchProjectVisualizations() returns the visualization id and createdOn timestamp, but the file list and (critically) the parameters are null.

I need the parameters! Because I need to show the description/title fields on the Project Page. But really all of the project details should be in this returned JSON right? 

Is there a different way I should be doing this?

**Comment by Janekdererste** [comment]
This is goint to be solved on the front end. Just have separate Api calls with or without authentication
